### ISSUE TITLE
Possible undefined macro AS_VERSION and AS_NANO in configure.ac

### ISSUE THREAD

**Issue by czchen** [epico/ibus-libzhuyin#1]
Just report here since https://github.com/libzhuyin/ibus-libzhuyin does not enable issue.

I just clone the code and run `autogen.sh`. The following error shows up:

```
configure.ac:41: error: possibly undefined macro: AS_VERSION
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:42: error: possibly undefined macro: AS_NANO
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

**Comment by epico** [comment]
I just enabled the github.com ibus-libzhuyin issue report.

BTW, the ibus-libzhuyin is in development, not released any tab ball yet.

Maybe you need to install some packages to run autogen.sh.

**Comment by epico** [comment]
Sorry, my mistake.

The as-version.m4 and boost.m4 files are added to git repo.
https://github.com/epico/ibus-libzhuyin

**Comment by epico** [comment]
Is it okay to close this issue?
