### ISSUE TITLE
HELP/编译问题

### ISSUE THREAD

**Issue by xukai2025** [epico/ibus-libzhuyin#2]
`checking for IBUS... yes
checking for LIBZHUYIN... no
configure: error: Package requirements (
    libzhuyin >= 2.2.0
) were not met:

No package 'libzhuyin' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables LIBZHUYIN_CFLAGS
and LIBZHUYIN_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

`

**Comment by epico** [comment]
The libzhuyin code is merged into libpinyin project.
